- extensions.json
**IMPORTANT:** Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
> add dddice to extensions list

- extensions.json
**IMPORTANT:** Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
> Add C&S 5e AP Tracker to extensions list

- extensions.json
> Add Character Distances

- extensions.json
- [✅] A link to the raw github markdown file with a YAML front matter definition containing:
- [ ✅] The title of your extension
- [ ✅] A description of your extension
- [✅ ] The author
- [✅ ] A hero image
- [✅ ] An icon
- [ ✅] Tags (these will help with your extension's discoverability)
- [ ✅] A link to your extensions manifest
- [ ✅] You have done your changes in a separate branch.
- [ ✅] You have a descriptive commit message with a short title (first line).
- [ ✅] You have only one commit (if not, squash them into one commit).
- [ ✅] Your pull request MUST target the `main` branch on this repository.
- [✅ ] Your pull request puts your extensions details as the last entry in the …
> add Token Counter

- extensions.json
> Add Dynamic Fog

- extensions.json
- [✅] A link to the raw github markdown file with a YAML front matter definition containing:
- [✅] The title of your extension
- [✅] A description of your extension
- [✅] The author
- [✅] A hero image
- [✅] An icon
- [✅] Tags (these will help with your extension's discoverability)
- [✅] A link to your extensions manifest
- [✅] You have done your changes in a separate branch.
- [✅] You have a descriptive commit message with a short title (first line).
- [✅] You have only one commit (if not, squash them into one commit).
- [✅] Your pull request MUST target the `main` branch on this repository.
- [✅] Your pull request puts your extensions details as the last entry in the extensions.json …
> add shadowdark character sheet extension

- extensions.json
- [✅] A link to the raw github markdown file with a YAML front matter definition containing:
- [✅] The title of your extension
- [✅] A description of your extension
- [✅] The author
- [✅] A hero image
- [✅] An icon
- [✅] Tags (these will help with your extension's discoverability)
- [✅] A link to your extensions manifest
- [✅] You have done your changes in a separate branch.
- [✅] You have a descriptive commit message with a short title (first line).
- [✅] You have only one commit (if not, squash them into one commit).
- [✅] Your pull request MUST target the `main` branch on this repository.
- [✅] Your pull request puts your extensions details as the last entry in the extensions.json …
> Clash to OBR Store

- extensions.json
- [✅] A link to the raw github markdown file with a YAML front matter definition containing:
- [✅] The title of your extension
- [✅] A description of your extension
- [✅] The author
- [✅] A hero image
- [✅] An icon
- [✅] Tags (these will help with your extension's discoverability)
- [✅] A link to your extensions manifest
- [✅] You have done your changes in a separate branch.
- [✅] You have a descriptive commit message with a short title (first line).
- [✅] You have only one commit (if not, squash them into one commit).
- [✅] Your pull request MUST target the `main` branch on this repository.
- [✅] Your pull request puts your extensions details as the last entry in the extensions.json …
> Rumble Chat extension to OBR Store

- extensions.json
> Add Witchdice to extensions.json

- extensions.json
> add "AoE Shapes" extention

- extensions.json
> PDF! Reader to OBR Store

- extensions.json
> add sit to extensions store

- extensions.json
> Add Marked! to OBR Store

- extensions.json
> Add Hp Tracker Extension to extensions.json

- extensions.json
> Add Last Fable and Ultimate Story Extensions for Fabula Ultima

- extensions.json
> Add DummySheet

- extensions.json
> Add dynamic fog importer extension

- extensions.json
> Scry! to OBR Store

- extensions.json
> Smoke & Spectre! to OBR Store

- extensions.json
---
This pull requests ignores the requirements as it it removing listings from the Extension Store
> Remove dynamic fog and dynamic fog import

- extensions.json
> add "default view" extension

- extensions.json
> add dashboard-maker to extensions.json

- extensions.json
> Add outliner extension

- extensions.json
> Add OwlClock extension to store

- extensions.json
> Add prefabs extension

- extensions.json
> Calendar to OBR Store

- extensions.json
> Bones! to OBR Store

- extensions.json
> Add Pretty Sordid to the store

- extensions.json
> Adds Token Text extension

- extensions.json
> Add Owl Trackers to the store

- extensions.json
> Journal! to the Owlbear Store

- extensions.json
> Added 'Map Location Key'

- extensions.json
> Adds Dragonbane Initiative

- extensions.json
> Added a new extension called shadow sheet

- extensions.json
> Adding Sheet from Beyond

- extensions.json
> add: chronicle! to OBR Store

- extensions.json
> add: Decked! to OBR Store

- extensions.json
Added External Links extension for attaching external links to characters, mounts, and props.
---
> Added External Links extension

- extensions.json
> Add Segmentable Ruler

- extensions.json
> Add weather

- extensions.json
> Add phases automated to the store

- extensions.json
> Add Token Auras

- extensions.json
> Add portals

- extensions.json
> Add DCC Helper extension

- extensions.json
> Add condition markers with patch for OBR 2.3

- extensions.json
> Add grimwild extension

- extensions.json
> Add Shadow Crawler extension to extensions.json

- extensions.json
> Add Embers extension

- extensions.json
> Add Auras and Emanations extension

- extensions.json
> add causality to extensions.json

- extensions.json
> Add Simple HP Tracker

- extensions.json
> Add draw steel tools to store

- extensions.json
> Add loot extension

- extensions.json
Added DS Dice to extensions.json
> Added DS Dice

- extensions.json
> Add Ranges
